[theme]
base = "light"
primaryColor = "#7C3AED"
backgroundColor = "#FFFFFF"        # wit pagina-achtergrond
secondaryBackgroundColor = "#EEF2FF"
textColor = "#000000"             # zwart (dat wilde je)
font = "sans serif"
