[theme]
base = "light"
primaryColor = "#16a34a"        # groene accentkleur voor knoppen / radiobuttons
backgroundColor = "#ffffff"     # pagina-achtergrond (wit)
secondaryBackgroundColor = "#ecfdf5" # lichtgroene “kaartjes” / container achtergrond
textColor = "#0f172a"           # donkere tekstkleur
font = "sans serif"
